_core:
  default_config_hash: NlDIUdPDDX0V4owUbxlYWoCwMZv_Wnv-wqzepvT5drs
langcode: bg
mode: process_untranslated
current_language_mode: default
untranslated_handler: no_link
hide_single_link: false
show_langcode: true
hide_single_link_block: 0
