_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: bg
uuid: a50944b8-ca1f-4b7d-90f5-8bd9d5701028
name: 'GMK Group'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/113
admin_compact_mode: false
weight_select_max: 100
default_langcode: bg
